"""Storage of data that will not change throughout the life cycle of the application."""

# pulled from https://ubntwiki.com/products/software/unifi-controller/api
DEVICETYPE_MAP = {
    "BZ2": "Access Point",
    "BZ2Long-Range": "Access Point Long-Range",
    "p2N": "PicoStation M2",
    "S216150": "Switch 16 (150W)",
    "S224250": "Switch 24 (250W)",
    "S224500": "Switch 24 (500W)",
    "S248500": "Switch 48 (500W)",
    "S248750": "Switch 48 (750W)",
    "S28150": "Switch 8 (150W)",
    "U2HSR": "Access Point Outdoor+",
    "U2IW": "Access Point In Wall",
    "U2L48": "Access Point Long-Range",
    "U2Lv2": "Access Point Long-Range",
    "U2M": "Access Point Mini",
    "U2O": "Access Point Outdoor",
    "U2S48": "Access Point",
    "U2Sv2": "Access Point v2",
    "U5O": "Access Point Outdoor 5G",
    "U7E": "Access Point AC",
    "U7EDU": "Access Point AC EDU",
    "U7Ev2": "Access Point AC v2",
    "U7HD": "Access Point HD",
    "U7IW": "Access Point AC In Wall",
    "U7IWP": "Access Point AC In Wall Pro",
    "U7Long-Range": "Access Point AC Long-Range",
    "U7LT": "Access Point AC Lite",
    "U7MP": "Access Point AC Mesh Pro",
    "U7MSH": "Access Point AC Mesh",
    "U7NHD": "Access Point nanoHD",
    "U7O": "Access Point AC Outdoor",
    "U7P": "Access Point Pro",
    "U7PG2": "Access Point AC Pro",
    "U7SHD": "Access Point SHD",
    "UAE6": "Access Point 6 Extender",
    "UAIW6": "Access Point 6 In Wall",
    "UAL6": "Access Point 6 Lite",
    "UALong-Range6": "Access Point 6 Long-Range",
    "UALong-Range6v2": "Access Point 6 Long-Range",
    "UALong-Range6v3": "Access Point 6 Long-Range",
    "UAM6": "Access Point 6 Mesh?",
    "UAP6": "Access Point WiFi 6 Long-Range",
    "UAP6MP": "Access Point WiFi 6 Pro",
    "UASXG": "Application Server XG",
    "UBB": "Building-to-Building Bridge",
    "UCK": "Cloud Key",
    "UCKG2": "Cloud Key Gen2",
    "UCKP": "Cloud Key Gen2 Plus",
    "UCK-v2": "Cloud Key",
    "UCK-v3": "Cloud Key",
    "UCMSH": "Access Point MeshXG",
    "UCXG": "Access Point XG",
    "UDC48X6": "Switch Leaf",
    "UDM": "Dream Machine",
    "UDMB": "Access Point BeaconHD",
    "UDMPRO": "Dream Machine Pro",
    "UDMSE": "Dream Machine Pro SE",
    "UFLHD": "Access Point Flex HD",
    "UGW3": "Security Gateway 3P",
    "UGW4": "Security Gateway 4P",
    "UGWHD4": "Security Gateway HD",
    "UGWXG": "Security Gateway XG 8",
    "UHDIW": "Access Point In-Wall HD",
    "ULTE": "LTE",
    "ULTEPEU": "LTE Pro",
    "ULTEPUS": "LTE Pro",
    "UP1": "SmartPower Plug",
    "UP4": "Phone X",
    "UP5": "Phone",
    "UP5c": "Phone",
    "UP5t": "Phone Pro",
    "UP5tc": "Phone Pro",
    "UP6": "SmartPower Strip",
    "UP7": "Phone Executive",
    "UP7c": "Phone Executive",
    "US16P150": "Switch 16 PoE (150W)",
    "US24": "Switch 24",
    "US24P250": "Switch 24 PoE (250W)",
    "US24P500": "Switch 24 PoE (500W)",
    "US24PL2": "Switch 24 L2 PoE",
    "US24PRO": "Switch Pro 24 PoE",
    "US24PRO2": "Switch Pro 24",
    "US48": "Switch 48",
    "US48P500": "Switch 48 PoE (500W)",
    "US48P750": "Switch 48 PoE (750W)",
    "US48PL2": "Switch 48 L2 PoE",
    "US48PRO": "Switch Pro 48 PoE",
    "US48PRO2": "Switch Pro 48",
    "US624P": "Switch Enterprise 24 PoE",
    "US6XG150": "Switch 6XG PoE (150W)",
    "US8": "Switch 8",
    "US8P150": "Switch 8 PoE (150W)",
    "US8P60": "Switch 8 PoE (60W)",
    "USC8": "Switch 8",
    "USC8P150": "Switch 8 PoE",
    "USC8P450": "Switch Industrial",
    "USC8P60": "Switch 8 (60W)",
    "USF5P": "Switch Flex",
    "USL16LP": "Switch Lite 16 PoE",
    "USL16P": "Switch 16 PoE",
    "USL24": "Switch 24",
    "USL24P": "Switch 24 PoE",
    "USL48": "Switch 48",
    "USL48P": "Switch 48 PoE",
    "USL8A": "Switch Aggregation",
    "USL8LP": "Switch Lite 8 PoE",
    "USL8MP": "Switch Mission Critical",
    "USMINI": "USW Flex Mini",
    "USPPDUP": "SmartPower Pro PDU",
    "USPRPS": "Redundant Power System",
    "USXG": "Switch 16XG",
    "UXBSDM": "WiFi BaseStation XG",
    "UXGPRO": "Next-Generation Gateway Pro",
    "UXSDM": "WiFi BaseStation XG",
}
